PROGRAM
    : STATEMENT END{YYACCEPT;}
    ;

CONDOPERATOR:
    | GREATER_THEN_EQUAL
    | LESS_THEN_EQUAL
    | EQUAL_THEN_EQUAL
    | NOT_EQUAL
    | LESS_THEN
    | GREATER_THEN

BLOCK:
    O_KEY STATEMENT C_KEY
    ;

STATEMENT 
    : LINE
    | STATEMENT STATEMENT
    ;

LINE 
    :ATTRIBUTION
    | FUNCTION
    | DECLARATION
    | EOL
    ;

ATTRIBUTION
    : IDENTIFIER EQUALS CALC EOL
    | IDENTIFIER EQUALS IDENTIFIER_CALC EOL
    ;

IDENTIFIER_CALC
    : IDENTIFIER PLUS IDENTIFIER
    | IDENTIFIER MINUS IDENTIFIER
    | IDENTIFIER DIVIDE IDENTIFIER
    | IDENTIFIER TIMES IDENTIFIER
    ;

CALC
    : NUMBER
    | CALC '+' CALC
    | CALC '-' CALC
    | CALC '/' CALC
    | CALC '*' CALC
    | '(' CALC ')'
    ;

FUNCTION
    : IDENTIFIER '(' IDENTIFIER ')' EOL
    ;

DECLARATION
    : TYPE IDENTIFIER EOL
    ;

TYPE
    : int
    | float
    ;

IDENTIFIER
    : [a-zA-Z_][_a-zA-Z0-9]*
    ;

NUMBER
    : [0-9]+(\.[0-9]+)?
    |[0-9]+
    ;
